#!/usr/bin/env python

import sys, os
import mp3

for path in sys.argv[1:]:
    try:
        for f in mp3.frames(open(path, 'r')):
            pass
    except mp3.MP3Error, v:
        print '%s: %s' % (path, v.args[0])
    sys.stdout.flush()
